# Generated by Django 5.0.1 on 2024-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_property_coordinate_alter_property_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sell_or_rent',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], max_length=50),
        ),
    ]
