# Generated by Django 5.0.1 on 2024-02-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_property_sell_or_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='facade',
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Apartment', 'شقة'), ('House', 'فلة'), ('Farm', 'مزرعة'), ('Floor', 'دور'), ('Istrahah', 'استراحة'), ('Land', 'أرض')], max_length=100),
        ),
    ]
