# Generated by Django 5.0.1 on 2024-03-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_property_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to='static/property_images/'),
        ),
        migrations.AlterField(
            model_name='propertyimages360',
            name='image360',
            field=models.ImageField(upload_to='static/property_images360/'),
        ),
    ]
