# Generated by Django 5.0.1 on 2024-03-07 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_propertyimages_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userimage', models.ImageField(upload_to='static/user_images/')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userimages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
