# Generated by Django 5.0.1 on 2024-03-17 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_userimages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='favorite',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.profile'),
        ),
        migrations.AlterField(
            model_name='property',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.profile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.profile'),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userimages', to='webapp.profile'),
        ),
    ]
