# Generated by Django 5.0.1 on 2024-03-29 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_profile_userimage_delete_userimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedby', to='webapp.property'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='webapp.profile'),
        ),
    ]
