# Generated by Django 5.0.1 on 2024-03-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_favorite_property_alter_favorite_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=50, null=True),
        ),
    ]
