# Generated by Django 5.0.1 on 2024-03-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_property_lat_property_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
