# Generated by Django 5.0.1 on 2024-03-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_property_lat_alter_property_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='coordinate',
        ),
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='lng',
            field=models.FloatField(),
        ),
    ]
