# Generated by Django 5.0.1 on 2024-05-09 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_remove_property_coordinate_alter_property_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='webapp.profile'),
        ),
    ]
