# Generated by Django 5.0.1 on 2024-05-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_property_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='number_of_sides',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
