# Generated by Django 5.0.1 on 2024-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_alter_property_number_of_sides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
