# Generated by Django 5.0.1 on 2024-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_alter_property_year_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
